// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: calc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_calc_proto protoreflect.FileDescriptor

const file_calc_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"calc.proto\x12\n" +
	"calculator\x1a\fprimes.proto\x1a\tsum.proto2\x8e\x01\n" +
	"\x11CalculatorService\x126\n" +
	"\x03Sum\x12\x16.calculator.SumRequest\x1a\x17.calculator.SumResponse\x12A\n" +
	"\x06Primes\x12\x19.calculator.PrimesRequest\x1a\x1a.calculator.PrimesResponse0\x01B7Z5github.com/AshrafAaref21/grpc-golang/calculator/protob\x06proto3"

var file_calc_proto_goTypes = []any{
	(*SumRequest)(nil),     // 0: calculator.SumRequest
	(*PrimesRequest)(nil),  // 1: calculator.PrimesRequest
	(*SumResponse)(nil),    // 2: calculator.SumResponse
	(*PrimesResponse)(nil), // 3: calculator.PrimesResponse
}
var file_calc_proto_depIdxs = []int32{
	0, // 0: calculator.CalculatorService.Sum:input_type -> calculator.SumRequest
	1, // 1: calculator.CalculatorService.Primes:input_type -> calculator.PrimesRequest
	2, // 2: calculator.CalculatorService.Sum:output_type -> calculator.SumResponse
	3, // 3: calculator.CalculatorService.Primes:output_type -> calculator.PrimesResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_calc_proto_init() }
func file_calc_proto_init() {
	if File_calc_proto != nil {
		return
	}
	file_primes_proto_init()
	file_sum_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_calc_proto_rawDesc), len(file_calc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calc_proto_goTypes,
		DependencyIndexes: file_calc_proto_depIdxs,
	}.Build()
	File_calc_proto = out.File
	file_calc_proto_goTypes = nil
	file_calc_proto_depIdxs = nil
}
